# System Architecture

```mermaid
classDiagram
    class PresentationLayer {
        +API Endpoints
        +Services
    }
    class BusinessLogicLayer {
        +User
        +Place
        +Amenity
        +Review
    }
    class PersistenceLayer {
        +Repository
        +Database
        +Storage
    }

    PresentationLayer --> BusinessLogicLayer : Facade Pattern
    BusinessLogicLayer --> PersistenceLayer : Database Operations
